//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xcat.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_XCAT_DIALOG                 102
#define IDS_CAPTION                     102
#define IDD_VFO                         102
#define IDS_COMM_INIT_FAIL              103
#define IDC_PROPERTIES                  107
#define IDR_MAINFRAME                   128
#define IDD_SCAN_ENABLE                 129
#define IDR_BATWING                     129
#define IDD_BAND_SCAN                   130
#define IDD_COMM_SETUP                  131
#define IDD_CONFIGURE                   134
#define IDD_DEBUG                       136
#define IDD_MODE_SEL                    138
#define IDD_NAME_EDIT                   144
#define IDD_COMM_SETUP1                 145
#define IDD_DOWNLOAD                    147
#define IDC_COM1                        253
#define IDC_COM2                        254
#define IDC_COM3                        255
#define IDC_COM4                        256
#define IDC_TX_PL                       1000
#define IDC_RX_PL                       1001
#define IDC_TX_OFFSET                   1002
#define IDC_TX_TIMEOUT                  1003
#define IDC_EDIT1                       1004
#define IDC_RX_FREQ                     1004
#define IDC_DEBUG_MSGS                  1004
#define IDC_TX_VCO_SPLIT_F              1004
#define IDC_MODE                        1004
#define IDC_XCAT_ADR                    1004
#define IDC_NAME                        1004
#define IDC_MSGS                        1004
#define IDC_EDIT2                       1005
#define IDC_SCAN_MODE1                  1005
#define IDC_TX_OFFSET_FREQ              1005
#define IDC_RX_VCO_SPLIT_F              1005
#define IDC_SCAN_MODE2                  1006
#define IDC_EDIT3                       1006
#define IDC_BAND_SCAN_BOTTOM            1006
#define IDC_SCAN_MODE3                  1007
#define IDC_HANG_TIME                   1007
#define IDC_CHECK4                      1008
#define IDC_FIXED_SCAN                  1008
#define IDC_CHECK5                      1009
#define IDC_CHECK6                      1010
#define IDC_SCAN_MODE11                 1010
#define IDC_CHECK7                      1011
#define IDC_SCAN_MODE32                 1011
#define IDC_CHECK8                      1012
#define IDC_SCAN_MODE31                 1012
#define IDC_COMBO1                      1013
#define IDC_PRIORITY_CHAN               1013
#define IDC_COM_PORT                    1013
#define IDC_SCAN_FREQ                   1014
#define IDC_CONTROL_SYS                 1014
#define IDC_BAND_SCAN_TOP               1015
#define IDC_OUT_0                       1015
#define IDC_BAND_SCAN_STEP              1016
#define IDC_OUT_1                       1016
#define IDC_LOCKOUT_LIST                1017
#define IDC_OUT_2                       1017
#define IDC_FIRMWARE_VER                1018
#define IDC_OUT_5                       1018
#define IDC_OUT_3                       1019
#define IDC_LOADER_VER                  1019
#define IDC_PL_SCAN                     1020
#define IDC_OUT_6                       1020
#define IDC_OUT_4                       1021
#define IDC_OUT_7                       1022
#define IDC_SEND_COS                    1024
#define IDC_BAND                        1025
#define IDC_RANGE1                      1028
#define IDC_RANGE2                      1030
#define IDC_BAND_SCAN                   1030
#define IDC_DO_PL_SCAN                  1031
#define IDC_DEFAULTS                    1031
#define IDC_COMPILED                    1032
#define IDC_DO_DPL_SCAN                 1032
#define IDC_TRANSFER_STATUS             1033
#define IDC_SCAN_MODE10                 1034
#define IDC_TB_ENABLED                  1036
#define IDC_SCAN_ENABLED                1037
#define IDC_EDIT_NAME                   1038
#define IDC_RX_PL_ENABLE                1041
#define IDC_RX_DPL_ENABLE               1042
#define IDC_TX_PL_ENABLE                1043
#define IDC_TX_DPL_ENABLE               1044
#define IDC_SCAN_MODE4                  1045
#define IDC_RX_DPL_ENABLE_INV           1045
#define IDC_SCAN_MODE5                  1046
#define IDC_TX_DPL_ENABLE_INV           1046
#define IDC_SCAN_MODE6                  1047
#define IDC_TX_OFFSET_LABEL             1047
#define IDC_CHECK9                      1048
#define IDC_SCAN_MODE30                 1048
#define IDC_TX_TIMEOUT_LABEL            1048
#define IDC_CHECK10                     1049
#define IDC_SCAN_MODE29                 1049
#define IDC_CHECK11                     1050
#define IDC_SCAN_MODE28                 1050
#define IDC_CHECK12                     1051
#define IDC_SCAN_MODE15                 1051
#define IDC_UF_AS_SQUELCH               1051
#define IDC_CHECK13                     1052
#define IDC_SCAN_MODE16                 1052
#define IDC_SQUELCH                     1052
#define IDC_UF_HAS_VOLUME               1052
#define IDC_SCAN_MODE7                  1053
#define IDC_SQUELCH_LABEL               1053
#define IDC_SCAN_MODE8                  1054
#define IDC_VOLUME                      1054
#define IDC_UPDATE_FIRMWARE             1054
#define IDC_SCAN_MODE9                  1055
#define IDC_VOLUME_LABEL                1055
#define IDC_DOWNLOAD_ADR                1055
#define IDC_CHECK14                     1056
#define IDC_SCAN_MODE23                 1056
#define IDC_UPDATED_BLOCKS              1056
#define IDC_CHECK15                     1057
#define IDC_SCAN_MODE25                 1057
#define IDC_VERIFIED_BLOCKS             1057
#define IDC_CHECK16                     1058
#define IDC_SCAN_MODE17                 1058
#define IDC_CHECK17                     1059
#define IDC_SCAN_MODE18                 1059
#define IDC_CHECK18                     1060
#define IDC_SCAN_MODE19                 1060
#define IDC_SCAN_MODE13                 1061
#define IDC_SCAN_MODE14                 1062
#define IDC_SCAN_MODE27                 1063
#define IDC_CHECK19                     1064
#define IDC_SCAN_MODE20                 1064
#define IDC_CHECK20                     1065
#define IDC_SCAN_MODE21                 1065
#define IDC_CHECK21                     1066
#define IDC_SCAN_MODE22                 1066
#define IDC_CHECK22                     1067
#define IDC_SCAN_MODE24                 1067
#define IDC_CHECK23                     1068
#define IDC_SCAN_MODE26                 1068
#define IDC_COMBO2                      1069
#define IDC_2ND_PRIORITY                1069
#define IDC_BAUDRATE                    1069
#define IDC_SCAN_MODE12                 1070

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
